# create cluster role to allow a service account to create kubernetes jobs
# here the namespace = couture-console and service account is the default one
apiVersion: v1
kind: Namespace
metadata:
  name: couture-console
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: couture-console
  name: job-control
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-control
subjects:
- kind: ServiceAccount
  name: default
  namespace: couture-console
roleRef:
  kind: ClusterRole
  name: job-control
  apiGroup: rbac.authorization.k8s.io
