apiVersion: v1
kind: Service
metadata:
  name: couture-console
  namespace: couture-console
spec:
  selector:
    app: couture-console
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couture-console
  namespace: couture-console
spec:
  selector:
    matchLabels:
      app: couture-console
  replicas: 1
  template:
    metadata:
      labels:
        app: couture-console
    spec:
      containers:
      - name: couture-console
        image: sidharthc/couture-console:0.0.1
        ports:
        - containerPort: 5000
